import { faMagnifyingGlass } from "@fortawesome/free-solid-svg-icons";
import Head from "next/head";
import BottomInfo from "../components/bottomInfo";
import Filter from "../components/filter";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Travel App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Filter />
      <div className="px-10 mt-16">
        <BottomInfo
          icon={faMagnifyingGlass}
          message={"Click search to get distances"}
        />
      </div>
    </div>
  );
}
